### PR TITLE
Added guild invite

### PR DESCRIPTION
**Pull request by PeTerExtention**

### CODE REVIEW

**Comment by ukcai696969** [comment]
what does it do?

**Review by ukcai696969 — APPROVED** [review]
seems ok

**Comment by msn-95** [comment]
[WARN] Errored botname (id) TypeError: Cannot read properties of undefined (reading 'send')

**Comment by gamer50082** [comment]
TypeError: Cannot read properties of undefined (reading 'send')

**Review by adh319 — APPROVED** [review]

**Pull request merged**
